# version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: pg-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: sazib
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

      # pgadmin is an ui for visual postgres database view; -> (optonal)
      # pgadmin:
      #   image: dpage/pgadmin4
      #   container_name: pgadmin
      #   restart: unless-stopped
      #   environment:
      #     PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      #     PGADMIN_DEFAULT_PASSWORD: admin123
      #   ports:
      #     - "5050:80"
      #   depends_on:
      #     - postgres

volumes:
  pgdata:

